version: '3.9'
services: 
  minecraft:
    restart: unless-stopped
    image: itzg/minecraft-server
    container_name: minecraft
    ports: 
      - 25565:25565
    volumes: 
      - ./data:/data
    environment: 
      - EULA=TRUE